Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -62,7 +62,7 @@ jobs:
           for each in `ls .`
           do
             cd "${each}" || exit 1
-            echo -e "{\n  \"name\": \"@huaweicloud/huaweicloud-sdk-${each}\",\n  \"version\": \"${version}\",\n  \"description\": \"Huaweicloud SDK for ${each}\",\n  \"main\": \"huaweicloud-sdk-${each}.js\",\n  \"typings\": \"huaweicloud-sdk-${each}.d.ts\",\n  \"scripts\": {\n    \"test\": \"echo \\\"Error: no test specified\\\" && exit 1\"\n  },\n  \"repository\": {\n    \"type\": \"git\",\n    \"url\": \"https://github.com/huaweicloud-sdk/huaweicloud-sdk-nodejs\"\n  },\n  \"author\": \"HuaweiCloud_SDK\",\n  \"license\": \"Apache-2.0\",\n  \"dependencies\": {\n    \"@huaweicloud/huaweicloud-sdk-core\": \"^${version}\"\n  }" >> package.json
+            echo -e "{\n  \"name\": \"@huaweicloud/huaweicloud-sdk-${each}\",\n  \"version\": \"${version}\",\n  \"description\": \"Huaweicloud SDK for ${each}\",\n  \"main\": \"huaweicloud-sdk-${each}.js\",\n  \"typings\": \"huaweicloud-sdk-${each}.d.ts\",\n  \"scripts\": {\n    \"test\": \"echo \\\"Error: no test specified\\\" && exit 1\"\n  },\n  \"repository\": {\n    \"type\": \"git\",\n    \"url\": \"https://github.com/huaweicloud-sdk/huaweicloud-sdk-nodejs\"\n  },\n  \"author\": \"HuaweiCloud_SDK\",\n  \"license\": \"Apache-2.0\",\n  \"dependencies\": {\n    \"@huaweicloud/huaweicloud-sdk-core\": \"^${version}\"\n  }\n}" > package.json
             $npm_publish
             cd - || exit 1
           done
